name = "ruanimports"
main = "src/index.js"
compatibility_date = "2026-08-01"

[[d1_databases]]
binding = "DB"
database_name = "ruanimports-db"
database_id = "dd32f6e8-f310-4c12-ae83-d85d1ba379c4"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]
not_found_handling = "404-page"
